# Generated by Django 3.0.4 on 2020-04-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modeltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productionyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('R', 'Robot')], default='A', max_length=2)),
                ('color', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlist.Manufacturer')),
                ('models_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlist.Modeltype')),
                ('production_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlist.Productionyear')),
            ],
        ),
    ]
